create table fs_company_info (
	id bigint generated by default as identity (start with 1), 
	company_code varchar(255) not null, 
	company_name varchar(255) not null, 
	market_type varchar(255), 
	company_type varchar(255), 
	capital varchar(255), 
	board_url varchar(255), 
	modify_date varchar(255), 
	created_at timestamp, 
	updated_at timestamp, 
	primary key (id)
)

create table fs_outside_stock_info (
	id bigint generated by default as identity (start with 1), 
	company_code varchar(255), 
	company_name varchar(255) not null, 
	today_reply_cnt bigint, 
	save_date timestamp, 
	compnay_info_id bigint, 
	primary key (id)
)

alter table fs_company_info add constraint UK_fs_company_info  unique (company_code);
alter table fs_outside_stock_info add constraint FK_fs_outside_stock_info foreign key (compnay_info_id) references fs_company_info;

--
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10001', '환스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10002', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10003', '환스컴퍼니', '비상장', 'SI', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10004', '용스컴퍼니', '비상장', 'QA', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10005', '환스컴퍼니', '비상장', 'WS', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10006', '용스컴퍼니', '비상장', 'SI', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10007', '환스컴퍼니', '비상장', 'OO', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10008', '용스컴퍼니', '비상장', 'SS', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10009', '환스컴퍼니', '비상장', 'AA', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10010', '용스컴퍼니', '비상장', 'BB', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10011', '환스컴퍼니', '비상장', 'CC', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10012', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10013', '환스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10014', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10015', '환스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10016', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10017', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10018', '환스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10019', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10020', '환스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10021', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--insert into fs_company_info(company_code, company_name, market_type, company_type, capital, board_url, modify_date, created_at) values ('10022', '용스컴퍼니', '비상장', 'IT', '500억', 'http://38.co.kr', '2015-07-01', now());
--
--
--
--#insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10001', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10002', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10003', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10004', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10005', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10006', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10007', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10008', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10009', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10010', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10011', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10012', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10013', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10014', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10015', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10016', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10017', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10018', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10019', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10020', '환스컴퍼니', 100, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10021', '용스컴퍼니', 150, now());
--insert into fs_outside_stock_info(company_code, company_name, today_reply_cnt, save_date) values ('10022', '용스컴퍼니', 150, now());